### ISSUE TITLE
Run `generate-index.py` inside Docker

### ISSUE THREAD

**Issue by hgoldstein** [huntergoldstein/aquila#4]
- [x] Provide method to run `generate-index.py` inside Docker
- [x] Add Grunt task to rebuild index on file change

**Comment by hgoldstein** [comment]
The second task is going to be slightly more involved. The best way is probably leveraging [grunt-exec](https://www.npmjs.com/package/grunt-exec). We can store the slides directory in an environment variable.

**Comment by orangeturtle739** [comment]
https://github.com/huntergoldstein/aquila/commit/5cc469f14e2544365e513f05d6e7ba96665ecec5
:tophat:
