### ISSUE TITLE
Binary space partitioning slide layout

### ISSUE THREAD

**Issue by orangeturtle739** [huntergoldstein/aquila#5]
Make something that lets any markdown slide be divided into any number of binary partitions along either axis, with each partition containing a slide.

**Comment by hgoldstein** [comment]
I'm playing around with patching `marked.js` to add syntax for (at least) columns, see this gist: https://gist.github.com/huntergoldstein/41c0b98c2bb794b0c9d3b758cda92d9f.

The formatting (right now) is something like:
```
% * Foo
%%%
% * Bar
```
This is not great. Something like:
```
Foo | Bar
```
might be preferred. Or even just `%%%` (or some other sequence) with some sort of delimiter (versus writing `%` on every line).

**Comment by hgoldstein** [comment]
Also see: https://github.com/huntergoldstein/aquila/tree/hdg-columns_patch.

**Comment by orangeturtle739** [comment]
This is super cool!

**Comment by hgoldstein** [comment]
This is fairly hacky; before adding ratios and vertical vs horizontal partitions I want to try and make it more idiomatic w.r.t. the markdown parser.

**Comment by orangeturtle739** [comment]
Horizontal is good enough.
