### ISSUE TITLE
Convert scripts in bin to pure python

### ISSUE THREAD

**Issue by orangeturtle739** [huntergoldstein/aquila#7]
The scripts in [`bin`](https://github.com/huntergoldstein/aquila/tree/master/bin) currently use a mixture of python and bash. If we make them completely python, then we:
* Remove 1 dependency.
* Don't have the worry about bash differences between Linux and MacOS (the reason some lines are currently in python).
* Possibly allow Aquila to work on windows (but docker provides a bash shell, so it might work anyway).

**Comment by hgoldstein** [comment]
Right now I'm going through and just changing each file in `bin` to do the same thing (but in Python). Going to condense the commands into a single file (or at least one entry point).

**Comment by orangeturtle739** [comment]
Resolved by https://github.com/huntergoldstein/aquila/pull/9.
